class MockData {
  // Mock platforms data
  static final List<Map<String, dynamic>> platforms = [
    {
      'id': 'coursera',
      'name': 'Coursera',
      'logoUrl': 'https://d3njjcbhbojbot.cloudfront.net/web/images/icons/favicons/android-chrome-512x512.png',
      'description': 'Coursera offers courses, specializations, certificates, and degrees from top universities and companies.',
      'hasFreeContent': true,
      'specialties': ['Computer Science', 'Business', 'Data Science', 'Healthcare'],
    },
    {
      'id': 'udemy',
      'name': 'Udemy',
      'logoUrl': 'https://www.udemy.com/staticx/udemy/images/v7/logo-udemy.svg',
      'description': 'Udemy is an online learning platform with courses taught by real-world experts.',
      'hasFreeContent': true,
      'specialties': ['Development', 'IT & Software', 'Music', 'Marketing'],
    },
    {
      'id': 'edx',
      'name': 'edX',
      'logoUrl': 'https://www.edx.org/images/logos/edx-logo-elm.svg',
      'description': 'edX offers courses from top universities around the world, including many free options.',
      'hasFreeContent': true,
      'specialties': ['Computer Science', 'Data Science', 'Business Management', 'Languages'],
    },
    {
      'id': 'udacity',
      'name': 'Udacity',
      'logoUrl': 'https://www.udacity.com/images/partners/logo_udacity.png',
      'description': 'Udacity offers Nanodegree programs and certificates focused on in-demand tech skills.',
      'hasFreeContent': false,
      'specialties': ['Artificial Intelligence', 'Data Science', 'Programming', 'Cloud Computing'],
    },
    {
      'id': 'skillshare',
      'name': 'Skillshare',
      'logoUrl': 'https://static.skillshare.com/assets/images/logo-header-2020.svg',
      'description': 'Skillshare is an online learning community for creative and curious people.',
      'hasFreeContent': false,
      'specialties': ['Design', 'Photography', 'Creative Writing', 'Animation'],
    },
    {
      'id': 'pluralsight',
      'name': 'Pluralsight',
      'logoUrl': 'https://www.pluralsight.com/content/dam/pluralsight/newsroom/brand-assets/logos/PS_logo_F-01.png',
      'description': 'Pluralsight is a technology skills platform with assessments and learning paths.',
      'hasFreeContent': false,
      'specialties': ['Software Development', 'IT Ops', 'Security', 'Cloud Computing'],
    },
  ];

  // Mock courses data
  static final List<Map<String, dynamic>> courses = [
    {
      'id': 'cs101',
      'title': 'Introduction to Computer Science',
      'description': 'Learn the basics of computer science and programming. This course covers fundamental concepts like algorithms, data structures, and problem-solving techniques.',
      'instructor': 'Dr. David Patterson',
      'platformId': 'coursera',
      'platformName': 'Coursera',
      'price': 0.0,
      'rating': 4.8,
      'totalRatings': 25674,
      'durationInWeeks': 8,
      'level': 'beginner',
      'learningStyle': 'video',
      'hasCertificate': true,
      'skills': ['Python', 'Programming Basics', 'Algorithms', 'Problem Solving'],
      'imageUrl': 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/08/33f720502a11e59e72391aa537f5c9/pythonlearn_thumbnail_1x1.png?auto=format%2Ccompress&dpr=1',
      'courseUrl': 'https://www.coursera.org/learn/python',
    },
    {
      'id': 'ml101',
      'title': 'Machine Learning Fundamentals',
      'description': 'An introduction to machine learning concepts and applications. You\'ll learn about supervised and unsupervised learning, neural networks, and how to implement ML algorithms.',
      'instructor': 'Andrew Ng',
      'platformId': 'coursera',
      'platformName': 'Coursera',
      'price': 49.99,
      'rating': 4.9,
      'totalRatings': 154893,
      'durationInWeeks': 12,
      'level': 'intermediate',
      'learningStyle': 'interactive',
      'hasCertificate': true,
      'skills': ['Machine Learning', 'Python', 'Data Analysis', 'Neural Networks'],
      'imageUrl': 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/08/65a3d0a2be11e8b2dbf7fe8666e6d4/Machine-Learning-Course-Thumbnail---1-.png?auto=format%2Ccompress&dpr=1',
      'courseUrl': 'https://www.coursera.org/learn/machine-learning',
    },
    {
      'id': 'web101',
      'title': 'Web Development Bootcamp',
      'description': 'A comprehensive web development course that covers HTML, CSS, JavaScript, and modern frameworks. You\'ll build real projects and learn best practices.',
      'instructor': 'Colt Steele',
      'platformId': 'udemy',
      'platformName': 'Udemy',
      'price': 19.99,
      'rating': 4.7,
      'totalRatings': 215684,
      'durationInWeeks': 10,
      'level': 'beginner',
      'learningStyle': 'project-based',
      'hasCertificate': true,
      'skills': ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
      'imageUrl': 'https://img-c.udemycdn.com/course/480x270/625204_436a_3.jpg',
      'courseUrl': 'https://www.udemy.com/course/the-web-developer-bootcamp/',
    },
    {
      'id': 'py201',
      'title': 'Advanced Python Programming',
      'description': 'Take your Python skills to the next level with advanced topics like concurrency, design patterns, and optimization techniques.',
      'instructor': 'Jose Portilla',
      'platformId': 'udemy',
      'platformName': 'Udemy',
      'price': 29.99,
      'rating': 4.6,
      'totalRatings': 34521,
      'durationInWeeks': 6,
      'level': 'advanced',
      'learningStyle': 'video',
      'hasCertificate': true,
      'skills': ['Python', 'Concurrency', 'Design Patterns', 'Code Optimization'],
      'imageUrl': 'https://img-c.udemycdn.com/course/480x270/2473048_8255_5.jpg',
      'courseUrl': 'https://www.udemy.com/course/complete-python-bootcamp/',
    },
    {
      'id': 'ds101',
      'title': 'Data Science Essentials',
      'description': 'An introduction to data science principles and tools. Learn about data analysis, visualization, and how to extract insights from data.',
      'instructor': 'Dr. Charles Russell',
      'platformId': 'edx',
      'platformName': 'edX',
      'price': 0.0,
      'rating': 4.5,
      'totalRatings': 22361,
      'durationInWeeks': 6,
      'level': 'beginner',
      'learningStyle': 'interactive',
      'hasCertificate': false,
      'skills': ['Data Science', 'Python', 'Data Visualization', 'Statistics'],
      'imageUrl': 'https://prod-discovery.edx-cdn.org/media/course/image/3feaafc3-270e-427a-bd57-d6a01df4a6e6-7c2a7a1caf35.small.png',
      'courseUrl': 'https://www.edx.org/professional-certificate/python-data-science',
    },
    {
      'id': 'cs201',
      'title': 'Algorithms and Data Structures',
      'description': 'A deep dive into algorithms and data structures. This course focuses on algorithm design, analysis, and implementation in various programming languages.',
      'instructor': 'Tim Roughgarden',
      'platformId': 'coursera',
      'platformName': 'Coursera',
      'price': 79.99,
      'rating': 4.7,
      'totalRatings': 15638,
      'durationInWeeks': 12,
      'level': 'intermediate',
      'learningStyle': 'video',
      'hasCertificate': true,
      'skills': ['Algorithms', 'Data Structures', 'Problem Solving', 'Programming'],
      'imageUrl': 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/67/9a1240b7dd11e7a6ae67047b944e5b/Logo_Square.png?auto=format%2Ccompress&dpr=1',
      'courseUrl': 'https://www.coursera.org/specializations/algorithms',
    },
    {
      'id': 'ai101',
      'title': 'Introduction to Artificial Intelligence',
      'description': 'An overview of artificial intelligence concepts, applications, and implications. Learn about AI algorithms, machine learning, and ethical considerations.',
      'instructor': 'Sebastian Thrun',
      'platformId': 'udacity',
      'platformName': 'Udacity',
      'price': 399.0,
      'rating': 4.8,
      'totalRatings': 9452,
      'durationInWeeks': 16,
      'level': 'intermediate',
      'learningStyle': 'project-based',
      'hasCertificate': true,
      'skills': ['Artificial Intelligence', 'Machine Learning', 'Computer Vision', 'Ethics in AI'],
      'imageUrl': 'https://d20vrrgs8k4bvw.cloudfront.net/images/courses/thumbnails/ud090-en-US.jpg',
      'courseUrl': 'https://www.udacity.com/course/intro-to-artificial-intelligence--cs271',
    },
    {
      'id': 'design101',
      'title': 'UI/UX Design Fundamentals',
      'description': 'Learn the principles of user interface and user experience design. This course covers design thinking, wireframing, prototyping, and user testing.',
      'instructor': 'Jessica Harllee',
      'platformId': 'skillshare',
      'platformName': 'Skillshare',
      'price': 15.0,
      'rating': 4.6,
      'totalRatings': 8621,
      'durationInWeeks': 4,
      'level': 'beginner',
      'learningStyle': 'interactive',
      'hasCertificate': false,
      'skills': ['UI Design', 'UX Design', 'Wireframing', 'Figma', 'Design Thinking'],
      'imageUrl': 'https://static.skillshare.com/uploads/project/373b87f08e6a1c582fc7ddfd7e798c15/a56dbc1a',
      'courseUrl': 'https://www.skillshare.com/classes/UI-UX-Design-Creating-User-Experiences/1386393658',
    },
    {
      'id': 'cloud101',
      'title': 'Cloud Computing Fundamentals',
      'description': 'An introduction to cloud computing concepts, services, and providers. Learn about AWS, Azure, and Google Cloud, and how to deploy applications to the cloud.',
      'instructor': 'Ben Piper',
      'platformId': 'pluralsight',
      'platformName': 'Pluralsight',
      'price': 29.0,
      'rating': 4.5,
      'totalRatings': 6835,
      'durationInWeeks': 8,
      'level': 'beginner',
      'learningStyle': 'video',
      'hasCertificate': true,
      'skills': ['Cloud Computing', 'AWS', 'Azure', 'DevOps', 'Deployment'],
      'imageUrl': 'https://pluralsight.imgix.net/course-images/aws-certified-cloud-practitioner-2020-v1.jpg',
      'courseUrl': 'https://www.pluralsight.com/paths/aws-certified-cloud-practitioner',
    },
    {
      'id': 'mobile101',
      'title': 'Mobile App Development with Flutter',
      'description': 'Learn to build beautiful, natively compiled applications for mobile, web, and desktop from a single codebase with Flutter and Dart.',
      'instructor': 'Angela Yu',
      'platformId': 'udemy',
      'platformName': 'Udemy',
      'price': 24.99,
      'rating': 4.8,
      'totalRatings': 42365,
      'durationInWeeks': 12,
      'level': 'intermediate',
      'learningStyle': 'project-based',
      'hasCertificate': true,
      'skills': ['Flutter', 'Dart', 'Mobile Development', 'UI Design', 'Cross-platform'],
      'imageUrl': 'https://img-c.udemycdn.com/course/480x270/1708340_7108_4.jpg',
      'courseUrl': 'https://www.udemy.com/course/flutter-bootcamp-with-dart/',
    },
    {
      'id': 'blockchain101',
      'title': 'Blockchain Fundamentals',
      'description': 'An introduction to blockchain technology and its applications. Learn about distributed ledgers, smart contracts, and cryptocurrency.',
      'instructor': 'Bettina Warburg',
      'platformId': 'edx',
      'platformName': 'edX',
      'price': 99.0,
      'rating': 4.4,
      'totalRatings': 3268,
      'durationInWeeks': 6,
      'level': 'beginner',
      'learningStyle': 'video',
      'hasCertificate': true,
      'skills': ['Blockchain', 'Cryptocurrency', 'Smart Contracts', 'Distributed Systems'],
      'imageUrl': 'https://prod-discovery.edx-cdn.org/media/course/image/ce0e36e0-af05-4f67-ae1b-0e91a470acb8-3b61c28f1a62.small.jpg',
      'courseUrl': 'https://www.edx.org/course/blockchain-fundamentals',
    },
    {
      'id': 'security101',
      'title': 'Cybersecurity Essentials',
      'description': 'Learn the fundamentals of cybersecurity including network security, cryptography, and ethical hacking techniques.',
      'instructor': 'Troy Hunt',
      'platformId': 'pluralsight',
      'platformName': 'Pluralsight',
      'price': 35.0,
      'rating': 4.7,
      'totalRatings': 9532,
      'durationInWeeks': 10,
      'level': 'intermediate',
      'learningStyle': 'interactive',
      'hasCertificate': true,
      'skills': ['Cybersecurity', 'Network Security', 'Ethical Hacking', 'Cryptography'],
      'imageUrl': 'https://pluralsight.imgix.net/course-images/ethical-hacking-understanding-v1.jpg',
      'courseUrl': 'https://www.pluralsight.com/paths/ethical-hacking',
    },
    {
      'id': 'business101',
      'title': 'Business Strategy Fundamentals',
      'description': 'Learn the basics of business strategy, including market analysis, competitive positioning, and strategic planning.',
      'instructor': 'Michael Porter',
      'platformId': 'coursera',
      'platformName': 'Coursera',
      'price': 49.0,
      'rating': 4.6,
      'totalRatings': 18754,
      'durationInWeeks': 5,
      'level': 'beginner',
      'learningStyle': 'video',
      'hasCertificate': true,
      'skills': ['Business Strategy', 'Market Analysis', 'Strategic Planning', 'Leadership'],
      'imageUrl': 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/06/38a6e0158911e7a5ee253f17ea9fed/WH-Square.png?auto=format%2Ccompress&dpr=1',
      'courseUrl': 'https://www.coursera.org/learn/strategic-business-management',
    },
    {
      'id': 'graphics101',
      'title': 'Digital Illustration for Beginners',
      'description': 'Learn the fundamentals of digital illustration using industry-standard tools like Adobe Illustrator and Procreate.',
      'instructor': 'Lisa Bardot',
      'platformId': 'skillshare',
      'platformName': 'Skillshare',
      'price': 10.0,
      'rating': 4.9,
      'totalRatings': 12653,
      'durationInWeeks': 3,
      'level': 'beginner',
      'learningStyle': 'project-based',
      'hasCertificate': false,
      'skills': ['Digital Illustration', 'Adobe Illustrator', 'Procreate', 'Drawing', 'Design'],
      'imageUrl': 'https://static.skillshare.com/uploads/project/4d839f9f60802d7f9b7a358423e98057/b0640da0',
      'courseUrl': 'https://www.skillshare.com/classes/Digital-Illustration-Learn-to-Use-Procreate/1712436004',
    },
    {
      'id': 'python101',
      'title': 'Python for Data Science',
      'description': 'Learn how to use Python for data analysis, visualization, and machine learning. This course covers pandas, NumPy, Matplotlib, and scikit-learn.',
      'instructor': 'Daniel Chen',
      'platformId': 'edx',
      'platformName': 'edX',
      'price': 0.0,
      'rating': 4.7,
      'totalRatings': 28965,
      'durationInWeeks': 8,
      'level': 'intermediate',
      'learningStyle': 'interactive',
      'hasCertificate': false,
      'skills': ['Python', 'Data Analysis', 'Pandas', 'NumPy', 'Data Visualization'],
      'imageUrl': 'https://prod-discovery.edx-cdn.org/media/course/image/da1b2400-322b-459b-97b0-0c557f05d017-b52fbbaf7aa7.small.png',
      'courseUrl': 'https://www.edx.org/course/python-for-data-science',
    },
    {
      'id': 'devops101',
      'title': 'DevOps Engineering Course',
      'description': 'Master DevOps practices, tools, and methodologies. Learn about CI/CD, containerization, infrastructure as code, and automation.',
      'instructor': 'James Turnbull',
      'platformId': 'udacity',
      'platformName': 'Udacity',
      'price': 499.0,
      'rating': 4.6,
      'totalRatings': 4587,
      'durationInWeeks': 16,
      'level': 'advanced',
      'learningStyle': 'project-based',
      'hasCertificate': true,
      'skills': ['DevOps', 'CI/CD', 'Docker', 'Kubernetes', 'Infrastructure as Code'],
      'imageUrl': 'https://d20vrrgs8k4bvw.cloudfront.net/images/courses/thumbnails/ud611-en-US.jpg',
      'courseUrl': 'https://www.udacity.com/course/cloud-dev-ops-nanodegree--nd9991',
    },
  ];
}